<?php

declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

use League\CommonMark\Environment\Environment;
use League\CommonMark\Extension\CommonMark\CommonMarkCoreExtension;
use League\CommonMark\Extension\GithubFlavoredMarkdownExtension;
use League\CommonMark\MarkdownConverter;

// ─── Markdown converter ───────────────────────────────────────────────────────

$environment = new Environment(['html_input' => 'allow', 'allow_unsafe_links' => false]);
$environment->addExtension(new CommonMarkCoreExtension());
$environment->addExtension(new GithubFlavoredMarkdownExtension());
$converter = new MarkdownConverter($environment);

// ─── Parse README.md ─────────────────────────────────────────────────────────

$readmePath = __DIR__ . '/README.md';

if (!file_exists($readmePath)) {
    fwrite(STDERR, "ERROR: README.md not found\n");
    exit(1);
}

$readme = str_replace("\r\n", "\n", (string) file_get_contents($readmePath));

/** @var array<string, array{icon: string, name: string, slug: string}> $categories */
$categories = [];

/** @var array<int, array{name: string, path: string, categorySlug: string, categoryName: string, categoryIcon: string, description: string, html: string}> $attributes */
$attributes = [];

$currentCategory = null;
$skipSections    = ['Notes', 'Contributing', 'Author', 'Install'];

foreach (explode("\n", $readme) as $line) {
    // Category heading: ## 📊 Eloquent (Models)
    if (preg_match('/^## (.+)$/', $line, $m)) {
        $raw  = trim($m[1]);
        $skip = false;

        foreach ($skipSections as $s) {
            if (str_contains($raw, $s)) {
                $skip = true;
                break;
            }
        }

        if ($skip) {
            $currentCategory = null;
            continue;
        }

        // Extract leading emoji grapheme cluster
        $icon = '';
        if (preg_match('/^(\X)/u', $raw, $em)) {
            $icon = $em[1];
        }

        $name = trim(mb_substr($raw, mb_strlen($icon)));
        $slug = trim(strtolower((string) preg_replace('/[^a-z0-9]+/i', '-', $name)), '-');

        $currentCategory      = compact('icon', 'name', 'slug');
        $categories[$slug] ??= $currentCategory;

        continue;
    }

    if ($currentCategory === null) {
        continue;
    }

    // Attribute line: * [`#[Table]`](attributes/eloquent/Table.md) — description
    if (preg_match('/^\*\s+\[`#\[([^\]]+)\]`\]\((attributes\/([^\/]+)\/[^)]+\.md)\)\s+[—–-]+\s+(.+)$/', $line, $m)) {
        $attributes[] = [
            'name'         => $m[1],
            'path'         => $m[2],
            'categorySlug' => $currentCategory['slug'],
            'categoryName' => $currentCategory['name'],
            'categoryIcon' => $currentCategory['icon'],
            'description'  => trim($m[4]),
            'html'         => '',
        ];
    }
}

// ─── Convert each .md file to HTML ───────────────────────────────────────────

foreach ($attributes as &$attr) {
    $file = __DIR__ . '/' . $attr['path'];

    if (!file_exists($file)) {
        fprintf(STDERR, "WARNING: %s not found\n", $attr['path']);
        continue;
    }

    $md = str_replace("\r\n", "\n", (string) file_get_contents($file));
    $md = (string) preg_replace('/\[←\s*Back to README\]\([^)]+\)/ui', '', $md);
    $md = trim($md);

    $attr['html'] = (string) $converter->convert($md);
}
unset($attr);

// ─── Build output ─────────────────────────────────────────────────────────────

$categoriesList = array_values($categories);

printf("Building: %d attributes across %d categories\n", count($attributes), count($categoriesList));

$jsonData = json_encode(
    ['categories' => $categoriesList, 'attributes' => $attributes],
    JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_THROW_ON_ERROR
);

file_put_contents(__DIR__ . '/index.html', buildHtml($jsonData));
echo "Done → index.html\n";

// ─── HTML template ────────────────────────────────────────────────────────────

function buildHtml(string $jsonData): string
{
    return <<<HTML
    <!DOCTYPE html>
    <!-- Auto-generated by build.php — do not edit manually -->
    <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Laravel PHP Attributes</title>
      <script src="https://cdn.tailwindcss.com"></script>
      <script>
        tailwind.config = {
          theme: {
            extend: {
              colors: { laravel: '#FF2D20' },
              fontFamily: { sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'] },
            }
          }
        }
      </script>
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" />
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github-dark.min.css" />
      <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/php.min.js"></script>
      <style>
        #panel { transform: translateX(100%); transition: transform 0.28s cubic-bezier(0.4,0,0.2,1); }
        #panel.open { transform: translateX(0); }
        #backdrop { opacity: 0; pointer-events: none; transition: opacity 0.28s ease; }
        #backdrop.open { opacity: 1; pointer-events: auto; }
        .card { transition: box-shadow 0.15s ease, transform 0.15s ease; }
        .card:hover { box-shadow: 0 8px 24px rgba(0,0,0,0.09); transform: translateY(-1px); }
        .md-content h1 { font-size: 1.35rem; font-weight: 700; margin-bottom: 0.75rem; color: #111827; }
        .md-content h2 { font-size: 1.05rem; font-weight: 600; margin-top: 1.5rem; margin-bottom: 0.5rem; color: #374151; }
        .md-content p { margin-bottom: 0.875rem; color: #374151; line-height: 1.7; }
        .md-content pre { margin: 1rem 0; border-radius: 0.5rem; overflow: auto; font-size: 0.82rem; }
        .md-content code:not(pre code) { background: #f3f4f6; color: #111827; padding: 0.15em 0.4em; border-radius: 0.3rem; font-size: 0.85em; font-family: monospace; }
        .md-content ul { list-style: disc; padding-left: 1.5rem; margin-bottom: 0.875rem; color: #374151; }
        .md-content li { margin-bottom: 0.25rem; line-height: 1.6; }
        .md-content hr { border-color: #e5e7eb; margin: 1.5rem 0; }
        .md-content a { color: #FF2D20; text-decoration: underline; }
        .md-content strong { color: #111827; }
        #panel-body::-webkit-scrollbar { width: 5px; }
        #panel-body::-webkit-scrollbar-track { background: #f9fafb; }
        #panel-body::-webkit-scrollbar-thumb { background: #d1d5db; border-radius: 10px; }
        @media (max-width: 640px) { #panel { width: 100vw !important; } }
      </style>
    </head>
    <body class="font-sans bg-gray-50 min-h-screen">

      <!-- Header -->
      <header class="bg-[#1C1C1E] shadow-lg sticky top-0 z-30">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex items-center justify-between">
          <div class="flex items-center gap-3">
            <span class="text-[#FF2D20] font-bold text-xl tracking-tight">Laravel</span>
            <span class="text-white/30 font-light text-xl">|</span>
            <span class="text-white font-medium text-lg">PHP Attributes</span>
          </div>
          <a href="https://github.com/MrPunyapal/laravel-attributes-list" target="_blank" rel="noopener noreferrer"
             class="flex items-center gap-2 text-white/70 hover:text-white transition-colors text-sm">
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
              <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.92.359.31.678.921.678 1.856 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd"/>
            </svg>
            GitHub
          </a>
        </div>
      </header>

      <!-- Controls -->
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-8 pb-4">
        <div class="relative mb-5">
          <svg class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
          </svg>
          <input id="search" type="text" placeholder="Search attributes…"
                 class="w-full pl-9 pr-4 py-2.5 bg-white border border-gray-200 rounded-xl text-sm text-gray-800 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-[#FF2D20]/40 focus:border-[#FF2D20] shadow-sm" />
        </div>
        <div id="filters" class="flex flex-wrap gap-2 mb-1"></div>
      </div>

      <!-- Grid -->
      <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
        <div id="count" class="text-xs text-gray-400 mb-4"></div>
        <div id="grid" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4"></div>
        <div id="empty" class="hidden text-center py-20 text-gray-400">
          <svg class="w-12 h-12 mx-auto mb-3 text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9.172 16.172a4 4 0 015.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/>
          </svg>
          <p class="text-sm font-medium">No attributes found</p>
        </div>
      </main>

      <!-- Backdrop -->
      <div id="backdrop" class="fixed inset-0 bg-black/40 z-40"></div>

      <!-- Side Panel -->
      <aside id="panel" class="fixed top-0 right-0 h-full w-full sm:w-[520px] bg-white z-50 flex flex-col shadow-2xl">
        <div class="bg-[#1C1C1E] flex items-center justify-between px-5 py-4 flex-shrink-0">
          <div>
            <div class="text-[#FF2D20] text-xs font-semibold uppercase tracking-widest mb-0.5" id="panel-category"></div>
            <h2 class="text-white font-bold text-base font-mono" id="panel-title"></h2>
          </div>
          <button id="close-panel" class="text-white/60 hover:text-white transition-colors p-1 rounded-lg hover:bg-white/10">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
            </svg>
          </button>
        </div>
        <div id="panel-body" class="flex-1 overflow-y-auto p-6">
          <div id="panel-content" class="md-content"></div>
        </div>
      </aside>

      <script>
        var DATA = $jsonData;

        var COLORS = [
          'bg-blue-100 text-blue-700',
          'bg-emerald-100 text-emerald-700',
          'bg-violet-100 text-violet-700',
          'bg-amber-100 text-amber-700',
          'bg-pink-100 text-pink-700',
          'bg-sky-100 text-sky-700',
          'bg-orange-100 text-orange-700',
          'bg-teal-100 text-teal-700',
          'bg-rose-100 text-rose-700',
          'bg-indigo-100 text-indigo-700',
        ];
        var colorMap = {};

        function getCategoryColor(slug) {
          if (!colorMap[slug]) {
            var idx = Object.keys(colorMap).length % COLORS.length;
            colorMap[slug] = COLORS[idx];
          }
          return colorMap[slug];
        }

        var activeCategory = 'all';
        var searchQuery    = '';
        var searchTimer    = null;

        function filterBtnClass(active) {
          return active
            ? 'inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-full text-sm font-medium bg-[#FF2D20] text-white shadow-sm cursor-pointer transition-all'
            : 'inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-full text-sm font-medium bg-white text-gray-600 border border-gray-200 hover:border-[#FF2D20] hover:text-[#FF2D20] cursor-pointer transition-all';
        }

        function renderFilters() {
          var container = document.getElementById('filters');

          var allBtn = document.createElement('button');
          allBtn.className    = filterBtnClass(true);
          allBtn.textContent  = 'All';
          allBtn.dataset.cat  = 'all';
          container.appendChild(allBtn);

          DATA.categories.forEach(function (cat) {
            var btn = document.createElement('button');
            btn.className   = filterBtnClass(false);
            btn.textContent = cat.icon + ' ' + cat.name;
            btn.dataset.cat = cat.slug;
            container.appendChild(btn);
          });

          container.addEventListener('click', function (e) {
            var btn = e.target.closest('button[data-cat]');
            if (!btn) return;
            activeCategory = btn.dataset.cat;
            container.querySelectorAll('button[data-cat]').forEach(function (b) {
              b.className = filterBtnClass(b.dataset.cat === activeCategory);
            });
            renderGrid();
          });
        }

        function getFiltered() {
          return DATA.attributes.filter(function (attr) {
            var matchCat = activeCategory === 'all' || attr.categorySlug === activeCategory;
            var q        = searchQuery.toLowerCase();
            var matchSearch = !q
              || attr.name.toLowerCase().indexOf(q) !== -1
              || attr.description.toLowerCase().indexOf(q) !== -1
              || attr.categoryName.toLowerCase().indexOf(q) !== -1;
            return matchCat && matchSearch;
          });
        }

        function renderGrid() {
          var grid     = document.getElementById('grid');
          var empty    = document.getElementById('empty');
          var countEl  = document.getElementById('count');
          var filtered = getFiltered();

          grid.innerHTML = '';
          countEl.textContent = filtered.length + ' attribute' + (filtered.length !== 1 ? 's' : '');

          if (filtered.length === 0) {
            grid.classList.add('hidden');
            empty.classList.remove('hidden');
            return;
          }

          grid.classList.remove('hidden');
          empty.classList.add('hidden');

          var frag = document.createDocumentFragment();

          filtered.forEach(function (attr) {
            var badgeColor = getCategoryColor(attr.categorySlug);
            var card       = document.createElement('div');
            card.className = 'card bg-white border border-gray-200 rounded-xl p-5 cursor-pointer select-none flex flex-col gap-3';

            // Name row
            var nameRow    = document.createElement('div');
            nameRow.className = 'flex items-start justify-between gap-2';

            var nameSpan       = document.createElement('span');
            nameSpan.className = 'font-mono font-bold text-[15px] text-gray-900 leading-snug break-all';
            nameSpan.textContent = '#[' + attr.name + ']';

            var arrow       = document.createElement('span');
            arrow.className = 'flex-shrink-0 text-gray-300 mt-0.5';
            arrow.innerHTML = '<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>';

            nameRow.appendChild(nameSpan);
            nameRow.appendChild(arrow);

            // Description
            var desc       = document.createElement('p');
            desc.className = 'text-gray-500 text-sm leading-relaxed flex-1';
            desc.textContent = attr.description;

            // Category badge
            var badgeWrap = document.createElement('div');
            var badge     = document.createElement('span');
            badge.className  = 'inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-medium ' + badgeColor;
            badge.textContent = attr.categoryIcon + ' ' + attr.categoryName;
            badgeWrap.appendChild(badge);

            card.appendChild(nameRow);
            card.appendChild(desc);
            card.appendChild(badgeWrap);

            card.addEventListener('click', (function (a) {
              return function () { openPanel(a); };
            }(attr)));

            frag.appendChild(card);
          });

          grid.appendChild(frag);
        }

        // ─── Side Panel ───────────────────────────────────────────────────────

        var panel    = document.getElementById('panel');
        var backdrop = document.getElementById('backdrop');

        function openPanel(attr) {
          document.getElementById('panel-title').textContent    = '#[' + attr.name + ']';
          document.getElementById('panel-category').textContent = attr.categoryIcon + ' ' + attr.categoryName;

          var content     = document.getElementById('panel-content');
          content.innerHTML = attr.html;

          // Apply syntax highlighting to all code blocks
          content.querySelectorAll('pre code').forEach(function (block) {
            hljs.highlightElement(block);
          });

          panel.classList.add('open');
          backdrop.classList.add('open');
          document.body.style.overflow = 'hidden';
          document.getElementById('panel-body').scrollTop = 0;
        }

        function closePanel() {
          panel.classList.remove('open');
          backdrop.classList.remove('open');
          document.body.style.overflow = '';
        }

        document.getElementById('close-panel').addEventListener('click', closePanel);
        backdrop.addEventListener('click', closePanel);
        document.addEventListener('keydown', function (e) {
          if (e.key === 'Escape') closePanel();
        });

        // ─── Search ───────────────────────────────────────────────────────────

        document.getElementById('search').addEventListener('input', function (e) {
          clearTimeout(searchTimer);
          var val = e.target.value;
          searchTimer = setTimeout(function () {
            searchQuery = val.trim();
            renderGrid();
          }, 150);
        });

        // ─── Boot ─────────────────────────────────────────────────────────────

        renderFilters();
        renderGrid();
      </script>
    </body>
    </html>
    HTML;
}
